spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:h2:./data/Banco.db;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        validator:
          apply_to_ddl: true